"""Add baton passing fields: is_final_round, llm_generated_feedback, previous_reviews_context

Revision ID: 3fb3353b9926
Revises: 57f36f9ba5ce
Create Date: 2026-05-05 23:26:01.194918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb3353b9926'
down_revision: Union[str, Sequence[str], None] = '57f36f9ba5ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reviews', sa.Column('llm_generated_feedback', sa.JSON(), nullable=True))
    op.add_column('interview_reviews', sa.Column('previous_reviews_context', sa.JSON(), nullable=True))
    op.add_column('interview_rounds', sa.Column('is_final_round', sa.Boolean(), nullable=False, server_default='false'))
    # Remove server_default after adding column (only needed for existing rows)
    op.alter_column('interview_rounds', 'is_final_round', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_rounds', 'is_final_round')
    op.drop_column('interview_reviews', 'previous_reviews_context')
    op.drop_column('interview_reviews', 'llm_generated_feedback')
    # ### end Alembic commands ###
