"""add interview_questions_snapshots table

Revision ID: 57f36f9ba5ce
Revises: 935ff819ec53
Create Date: 2026-04-30 03:11:28.530844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f36f9ba5ce'
down_revision: Union[str, Sequence[str], None] = '935ff819ec53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('interviewer_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('jd_based_questions', sa.JSON(), nullable=True),
    sa.Column('fundamental_questions', sa.JSON(), nullable=True),
    sa.Column('resume_questions', sa.JSON(), nullable=True),
    sa.Column('behavioral_questions', sa.JSON(), nullable=True),
    sa.Column('insights_based_questions', sa.JSON(), nullable=True),
    sa.Column('red_flag_probes', sa.JSON(), nullable=True),
    sa.Column('leetcode_questions', sa.JSON(), nullable=True),
    sa.Column('follow_up_topics', sa.JSON(), nullable=True),
    sa.Column('modified_by_interviewer', sa.Boolean(), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['interview_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_questions_snapshots')
    # ### end Alembic commands ###
